import Link from "next/link";
import { BugDemo } from "@/components/bug-demo";
import { SiteHeader, SiteFooter } from "@/components/site-shell";
export default function Home() {
  return <><SiteHeader/><main id="main-content" tabIndex={-1}>
    <section className="hero page-width"><div className="hero-copy"><h1>It’s broken.<br/><span>Find out why.</span></h1><p>Practice the part of programming tutorials skip. Open an unfamiliar project, follow the clues, and fix the bug hiding in the code.</p><div className="hero-actions"><Link className="button" href="/challenges">Pick your first bug</Link><a className="underlined" href="#how-it-works">How practice works</a></div><p className="hero-note">For students and junior engineers. JavaScript, React, and Express.</p></div><BugDemo/></section>
    <section id="how-it-works" className="workflow page-width"><h2>Less blank canvas.<br/>More detective work.</h2><ol><li><h3>Read the bug report</h3><p>A real symptom, a working project, and a file tree to explore. Start by figuring out what should happen.</p></li><li><h3>Trace it through the code</h3><p>Follow a request from the client to the server. Edit in the browser. Reveal a hint if you get stuck.</p></li><li><h3>Prove your fix</h3><p>Run the hidden tests against your changes. See the actual failures, then try again until the behavior is right.</p></li></ol></section>
    <section className="curriculum"><div className="page-width curriculum-inner"><div><h2>The bugs you’ll meet<br/>outside a tutorial.</h2><p>Eight focused challenges. Each starts with a different failure, so you build a debugging habit beyond a single fix.</p><Link className="button" href="/challenges">Explore the challenges</Link></div><ul><li><span>API contracts</span><span>A name that never appears</span></li><li><span>Async behavior</span><span>Old results replacing new ones</span></li><li><span>Authentication</span><span>A valid token getting rejected</span></li><li><span>React state</span><span>Clicks that don’t add up</span></li><li><span>And four more</span><span>Schema, config, pagination, errors</span></li></ul></div></section>
    <section className="closing page-width"><h2>Keep the lesson.<br/>Come back for the next bug.</h2><p>Create an account to save your code, track attempted and solved challenges, and see your progress by category.</p><Link className="button" href="/signup">Start your debugging practice</Link></section>
  </main><SiteFooter/></>;
}
